name: CI

on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  changes:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    outputs:
      src: ${{ steps.filter.outputs.src }}
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            src:
              - '.github/workflows/test.yml'
              - 'project/**'
              - '**.scala'
              - '**.sbt'
              - '**.conf'
              - '**.json'
              - '**.js'
              - '**.html'
              - '**.css'
              - '**.ts'
              - SCALA_VERSION
  code_format:
    name: Code format
    needs: changes
    if: ${{ needs.changes.outputs.src == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: scalafmt
        run: ./sbt scalafmtCheckAll
  test_scala_3:
    name: Scala 3
    needs: changes
    if: ${{ needs.changes.outputs.src == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '23'
          cache: sbt
      - name: Scala 3.x test
        run: ./sbt test
      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v5
        if: always() # always run even if the previous step fails
        with:
          report_paths: '**/target/test-reports/TEST-*.xml'
          check_name: Test Report Scala 3.x
          annotate_only: true
          detailed_summary: true
